# Generated by Django 4.2.17 on 2025-02-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_mark',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mark', to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='exam.examname'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classconfig'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exam_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examname'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exam_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examroom'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='graderule',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='forth_sub',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth_stu_name', to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='forth_sub',
            name='sub_conf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forth_sub', to='core.subjectconfig'),
        ),
        migrations.AddField(
            model_name='examname',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='classexam',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentclass'),
        ),
        migrations.AddField(
            model_name='classexam',
            name='exam_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examname'),
        ),
    ]
