# Generated by Django 4.2.17 on 2026-04-19 09:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0012_spinentry'),
        ('crucial', '0004_reporttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('distribution_type', models.CharField(choices=[('EQUAL_MONTHLY', 'Equal Monthly'), ('MANUAL', 'Manual')], default='EQUAL_MONTHLY', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Category',
                'verbose_name_plural': 'Budget Categories',
            },
        ),
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year_start', models.DateField()),
                ('year_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to='user.staffprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to='user.staffprofile')),
            ],
            options={
                'verbose_name': 'Budget Year',
                'verbose_name_plural': 'Budget Years',
                'ordering': ['-year_start'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='budget.budgetcategory')),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.staffprofile')),
            ],
            options={
                'verbose_name': 'Budget Revision',
                'ordering': ['-revised_at'],
            },
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='budget_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budgetyear'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='expense_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='crucial.expensehead'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='income_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='crucial.incomehead'),
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('WARNING', 'Warning (80%)'), ('CRITICAL', 'Critical (100%)'), ('OVERSPEND', 'Overspend (>100%)')], max_length=10)),
                ('threshold_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_at_trigger', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget.budgetcategory')),
            ],
            options={
                'verbose_name': 'Budget Alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetMonthlyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField()),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_locked', models.BooleanField(default=False)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_allocations', to='budget.budgetcategory')),
            ],
            options={
                'verbose_name': 'Monthly Allocation',
                'ordering': ['year', 'month'],
                'unique_together': {('budget_category', 'month', 'year')},
            },
        ),
    ]
