# Generated by Django 4.2.17 on 2025-02-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(default=None, max_length=30)),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='image')),
                ('institute_name', models.CharField(default=None, max_length=100)),
                ('institute_gender_type', models.CharField(choices=[('Combined', 'Combined'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Combined', max_length=8)),
                ('institute_eiin_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('institute_email_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('education_board_id', models.CharField(blank=True, max_length=100, null=True)),
                ('education_division_id', models.CharField(blank=True, max_length=100, null=True)),
                ('education_district_id', models.CharField(blank=True, max_length=100, null=True)),
                ('education_thana_id', models.CharField(blank=True, max_length=100, null=True)),
                ('headmaster_name', models.CharField(default=None, max_length=50)),
                ('headmaster_mobile', models.CharField(default=None, max_length=15)),
                ('incharge_manager', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('incharge_manager_mobile', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('incharge_manager_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('institute_address', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_web', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_management_web', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_fb', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('exam', models.CharField(blank=True, max_length=50, null=True)),
                ('e_roll', models.CharField(blank=True, max_length=20, null=True)),
                ('r_no', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_center', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_held_date', models.DateField(blank=True, max_length=50, null=True)),
                ('group_name', models.CharField(blank=True, max_length=40, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestmonialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('subbody', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('signature_name', models.CharField(blank=True, max_length=50, null=True)),
                ('head_master_signature', models.ImageField(blank=True, null=True, upload_to='signature')),
            ],
            options={
                'verbose_name_plural': 'Testmonial Settings',
            },
        ),
        migrations.CreateModel(
            name='WeekendDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, unique=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year')),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hour', models.IntegerField(default=8)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year')),
            ],
        ),
    ]
