# Generated by Django 4.2.17 on 2025-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name_in_bangla',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
