# Generated by Django 4.2.17 on 2025-02-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_customuser_name_in_bangla'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
