# Generated by Django 4.2.17 on 2026-06-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Gate K40-H', max_length=100)),
                ('device_type', models.CharField(choices=[('ZKTECO', 'ZKTeco')], default='ZKTECO', max_length=20)),
                ('ip_address', models.CharField(help_text='e.g. 192.168.1.201', max_length=50)),
                ('port', models.IntegerField(default=4370)),
                ('password', models.IntegerField(default=0, help_text='Comm key. Device e set na thakle 0 din.')),
                ('force_udp', models.BooleanField(default=False, help_text='Connect na hole eta True kore dekhun.')),
                ('timeout', models.IntegerField(default=10)),
                ('is_exit_device', models.BooleanField(default=False, help_text='Eta jodi ber howar gate er machine hoy tahole tick din.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=50)),
                ('punch_time', models.DateTimeField()),
                ('source', models.CharField(choices=[('FINGER', 'Fingerprint'), ('CARD', 'RFID Card'), ('PASSWORD', 'Password'), ('FACE', 'Face'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('raw_status', models.IntegerField(blank=True, null=True)),
                ('person_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('UNMATCHED', 'Unmatched')], default='UNMATCHED', max_length=10)),
                ('matched_user_id', models.BigIntegerField(blank=True, help_text='CustomUser.id jodi match hoy', null=True)),
                ('processed', models.BooleanField(default=False, help_text='Attendance + SMS process hoyeche kina')),
                ('sms_sent', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='device.biometricdevice')),
            ],
            options={
                'ordering': ['-punch_time'],
                'unique_together': {('device', 'device_user_id', 'punch_time')},
            },
        ),
    ]
