# Generated by Django 4.2.17 on 2025-02-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_commerz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='accounting_completed',
            field=models.BooleanField(default=False),
        ),
    ]
