# Generated by Django 4.2.17 on 2025-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_commerz', '0002_paymenttransaction_accounting_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
