# Generated by Django 4.2.17 on 2025-04-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_commerz', '0003_paymenttransaction_receipt_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.CharField(max_length=100)),
                ('merchant_password', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
            ],
        ),
    ]
