# Generated by Django 4.2.17 on 2025-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_commerz', '0004_trustbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('sslcommerz', 'SSLCommerz'), ('trustbank', 'Trust Bank')], default='sslcommerz', max_length=20),
        ),
    ]
