# Generated by Django 4.2.17 on 2025-12-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crucial', '0004_reporttask'),
        ('ssl_commerz', '0006_alter_paymenttransaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDisbursementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('trust_bank', 'Trust Bank'), ('bank_asia', 'Bank Asia'), ('dutch_bangla', 'Dutch Bangla Bank'), ('brac_bank', 'BRAC Bank'), ('city_bank', 'City Bank'), ('eastern_bank', 'Eastern Bank')], max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sslcz_ref_id', models.CharField(help_text='SSLCommerz generated reference ID for this bank account', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank Disbursement Account',
                'verbose_name_plural': 'Bank Disbursement Accounts',
            },
        ),
        migrations.CreateModel(
            name='DisbursementConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=200)),
                ('config_type', models.CharField(choices=[('manual', 'Manual Distribution'), ('percentage', 'Percentage Based'), ('fixed', 'Fixed Amount')], default='manual', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='disbursement_data',
            field=models.JSONField(blank=True, help_text='JSON data for bank disbursement distribution', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_disbursement_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trustbank',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TransactionDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_commerz.bankdisbursementaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='ssl_commerz.paymenttransaction')),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='disbursement_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssl_commerz.disbursementconfiguration'),
        ),
        migrations.CreateModel(
            name='FeeHeadBankDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of this fee head to go to this bank', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_commerz.bankdisbursementaccount')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crucial.feehead')),
            ],
            options={
                'verbose_name': 'Fee Head Bank Distribution',
                'verbose_name_plural': 'Fee Head Bank Distributions',
                'unique_together': {('bank_account', 'fee_head')},
            },
        ),
    ]
