# Generated by Django 4.2.17 on 2025-12-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_commerz', '0007_bankdisbursementaccount_disbursementconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdisbursementaccount',
            options={'verbose_name': 'SSLCommerz Bank Account', 'verbose_name_plural': 'SSLCommerz Bank Accounts'},
        ),
        migrations.RemoveField(
            model_name='bankdisbursementaccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='bankdisbursementaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bankdisbursementaccount',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='bankdisbursementaccount',
            name='routing_number',
        ),
        migrations.AddField(
            model_name='bankdisbursementaccount',
            name='display_name',
            field=models.CharField(default=0, help_text='Display name for admin interface', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdisbursementaccount',
            name='bank_name',
            field=models.CharField(choices=[('trust_bank', 'Trust Bank'), ('bank_asia', 'Bank Asia'), ('dutch_bangla', 'Dutch Bangla Bank'), ('brac_bank', 'BRAC Bank'), ('city_bank', 'City Bank'), ('eastern_bank', 'Eastern Bank'), ('standard_bank', 'Standard Bank'), ('one_bank', 'One Bank'), ('prime_bank', 'Prime Bank'), ('islami_bank', 'Islami Bank')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdisbursementaccount',
            name='sslcz_ref_id',
            field=models.CharField(help_text='SSLCommerz provided reference ID for this bank account', max_length=100, unique=True),
        ),
    ]
