# Generated by Django 4.2.17 on 2025-02-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_link_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('msg', models.TextField()),
            ],
        ),
    ]
