# Generated by Django 4.2.17 on 2025-02-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_public_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_msg',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
