# Generated by Django 4.2.17 on 2025-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_public_msg_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome_speech',
            old_name='text',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='welcome_speech',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
