# Generated by Django 4.2.17 on 2025-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_rename_text_welcome_speech_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcome_speech',
            name='heading',
        ),
        migrations.AddField(
            model_name='welcome_speech',
            name='text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
