# Generated by Django 4.2.17 on 2025-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentprofile',
            old_name='occupation',
            new_name='f_nid',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='f_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='father_name_bangla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='m_nid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='m_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='mother_name_bangla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='version',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], default='Bangla', max_length=8),
        ),
    ]
