# Generated by Django 4.2.17 on 2025-02-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0002_rename_occupation_parentprofile_f_nid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('FirstGrade', 'FirstGrade'), ('SecondGrade', 'SecondGrade'), ('ThirdGrade', 'ThirdGrade'), ('ForthGrade', 'ForthGrade'), ('FifthGrade', 'FifthGrade')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='job_nature',
            field=models.CharField(blank=True, choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='name_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_shift', to='core.studentshift'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='t_version',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], default='Bangla', max_length=8),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role', to='user.roletype'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_department', to='user.department'),
        ),
    ]
