# Generated by Django 4.2.17 on 2025-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_department_staffprofile_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
