# Generated by Django 4.2.17 on 2025-02-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_parentprofile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
