# Generated by Django 4.2.17 on 2025-02-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
