# Generated by Django 4.2.17 on 2025-06-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_commerz', '0005_paymenttransaction_gateway'),
        ('user', '0007_admissionapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplicant',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionapplicant',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplicant',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssl_commerz.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='admissionapplicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Payment Pending', 'Payment Pending')], default='Pending', max_length=60),
        ),
    ]
