# Generated by Django 4.2.17 on 2025-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_admissionapplicant_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_sought', models.CharField(default='Class XI', max_length=50)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day')], max_length=20)),
                ('version', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=20)),
                ('fullName', models.CharField(max_length=100, verbose_name="Applicant's Name [English]")),
                ('nickName', models.CharField(max_length=50, verbose_name='Nick Name')),
                ('brcn', models.CharField(max_length=50, verbose_name='Birth Register Certificate Number')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddha', 'Buddha')], max_length=20)),
                ('fullNameBangla', models.CharField(max_length=100, verbose_name="Applicant's Name [বাংলা]")),
                ('birthDate', models.DateField(verbose_name='Date of Birth')),
                ('bloodGroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('catchmentArea', models.BooleanField(default=False, verbose_name='Catchment Area')),
                ('quota', models.CharField(choices=[('N/A', 'N/A'), ('FQ', 'FQ'), ('EQ', 'EQ')], default='N/A', max_length=10)),
                ('previous_class', models.CharField(max_length=50, verbose_name='Previous Class')),
                ('boardRoll', models.CharField(max_length=50, verbose_name='Board Roll')),
                ('boardName', models.CharField(max_length=100, verbose_name='Board Name')),
                ('exam', models.CharField(default='SSC', max_length=20)),
                ('registrationNo', models.CharField(max_length=50, verbose_name='Reg No.')),
                ('gpa', models.CharField(max_length=10, verbose_name='GPA')),
                ('fatherName', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('fatherMobile', models.CharField(max_length=15, verbose_name="Father's Mobile")),
                ('fatherOccupation', models.CharField(max_length=100, verbose_name="Father's Occupation")),
                ('motherName', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('motherMobile', models.CharField(max_length=15, verbose_name="Mother's Mobile")),
                ('motherOccupation', models.CharField(max_length=100, verbose_name="Mother's Occupation")),
                ('smsAlertNumber', models.CharField(max_length=15, verbose_name='Mobile Number For Contact/SMS')),
                ('praddress', models.TextField(verbose_name='Present Address')),
                ('prCountry', models.CharField(max_length=50, verbose_name='Present Country')),
                ('prDistrict', models.CharField(max_length=50, verbose_name='Present District')),
                ('prThana', models.CharField(max_length=50, verbose_name='Present Thana/Upazilla')),
                ('prTelephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Present Telephone')),
                ('prMobile', models.CharField(max_length=15, verbose_name='Present Mobile')),
                ('paddress', models.TextField(verbose_name='Permanent Address')),
                ('pCountry', models.CharField(max_length=50, verbose_name='Permanent Country')),
                ('pDistrict', models.CharField(max_length=50, verbose_name='Permanent District')),
                ('pThana', models.CharField(max_length=50, verbose_name='Permanent Thana/Upazilla')),
                ('pTelephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Permanent Telephone')),
                ('pMobile', models.CharField(max_length=15, verbose_name='Permanent Mobile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
