# Generated by Django 4.2.17 on 2025-07-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_admissionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionform',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='version',
        ),
        migrations.AddField(
            model_name='admissionform',
            name='board_application_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Board Application ID'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='ex_rajuk_student',
            field=models.BooleanField(default=False, verbose_name='Ex-Rajuk Student'),
        ),
    ]
