# Generated by Django 4.2.17 on 2025-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_name', models.CharField(max_length=100)),
                ('spin_phone', models.CharField(max_length=20, unique=True)),
                ('spin_institute', models.CharField(max_length=200)),
                ('spin_num_students', models.IntegerField()),
                ('spin_result', models.IntegerField(blank=True, null=True)),
                ('spin_has_spun', models.BooleanField(default=False)),
            ],
        ),
    ]
