# Generated by Django 4.2.17 on 2026-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_spinentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
