# Generated by Django 4.2.17 on 2025-02-05 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crucial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waiver',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waiver',
            name='fee_types',
            field=models.ManyToManyField(related_name='waivers', to='crucial.feetype'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_waiver', to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tution_package',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='tution',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='tution',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='tution',
            name='tution_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crucial.tution_package'),
        ),
        migrations.AddField(
            model_name='transport_package',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='transport',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='transport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='transport',
            name='transport_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crucial.transport_package'),
        ),
        migrations.AddField(
            model_name='teachersubjectassign',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='teachersubjectassign',
            name='class_assigns',
            field=models.ManyToManyField(related_name='teacher_class_assignments', to='core.classconfig'),
        ),
        migrations.AddField(
            model_name='teachersubjectassign',
            name='subject_assigns',
            field=models.ManyToManyField(related_name='teacher_sub_assignments', to='core.subject'),
        ),
        migrations.AddField(
            model_name='teachersubjectassign',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_assign_teacher', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='salary_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_profiles', to='crucial.salaryprocess'),
        ),
        migrations.AddField(
            model_name='smslimit',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='crucial.smsusage'),
        ),
        migrations.AddField(
            model_name='sms',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='sms',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryprocess',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_pro_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryprocess',
            name='employee_salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_salary', to='crucial.salaryconfiguration'),
        ),
        migrations.AddField(
            model_name='salaryprocess',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryincrement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_increment_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryincrement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_increments', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='salaryincrement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_conf_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryconfiguration',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_conf', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='salaryconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routine',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_routine', to='core.classconfig'),
        ),
        migrations.AddField(
            model_name='routine',
            name='period_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_routine', to='core.periodconfig'),
        ),
        migrations.AddField(
            model_name='routine',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_routine', to='core.subject'),
        ),
        migrations.AddField(
            model_name='routine',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_routine', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='partialpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partialpayment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_payments', to='crucial.fees'),
        ),
        migrations.AddField(
            model_name='notification',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='notice',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeitemlist',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='incomeitemlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeitemlist',
            name='incometype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crucial.incomehead'),
        ),
        migrations.AddField(
            model_name='incomeitemlist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostel_package',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crucial.hostel_package'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_student', to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crucial.homework'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='homework',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='homework',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classconfig'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='feetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_type_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feetype',
            name='fee_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='crucial.feehead'),
        ),
        migrations.AddField(
            model_name='feetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_type_updator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feesubheadconfig',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='crucial.feehead'),
        ),
        migrations.AddField(
            model_name='feesubheadconfig',
            name='sub_heads',
            field=models.ManyToManyField(related_name='configurations', to='crucial.feesubhead'),
        ),
        migrations.AddField(
            model_name='feesubhead',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_heads', to='crucial.feehead'),
        ),
        migrations.AddField(
            model_name='fees_name',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='fees_name',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_name_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fees_name',
            name='fee_amount_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_name_amount', to='crucial.fee_package'),
        ),
        migrations.AddField(
            model_name='fees_name',
            name='fees_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_name_type', to='crucial.feetype'),
        ),
        migrations.AddField(
            model_name='fees_name',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_name_monthwise', to='crucial.fee_month'),
        ),
        migrations.AddField(
            model_name='fees_name',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_name_updator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fees',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='fees',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fees',
            name='feetype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crucial.fees_name'),
        ),
        migrations.AddField(
            model_name='fees',
            name='month_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_monthwise', to='crucial.fee_month'),
        ),
        migrations.AddField(
            model_name='fees',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='fees',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fee_package',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='fee_package',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_amount_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fee_package',
            name='fees_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_name_type_amount', to='crucial.feetype'),
        ),
        migrations.AddField(
            model_name='fee_package',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_amount_class', to='core.classgroupconfig'),
        ),
        migrations.AddField(
            model_name='fee_package',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_amount_updator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseitemlist',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='expenseitemlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseitemlist',
            name='expensetype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crucial.expensehead'),
        ),
        migrations.AddField(
            model_name='expenseitemlist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='download',
            name='academic_session_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicsession'),
        ),
        migrations.AddField(
            model_name='download',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='download',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classconfig'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='deduction_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crucial.deduction_type'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_deduction', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='advancesalarypayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='addition',
            name='addition_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crucial.addition_type'),
        ),
        migrations.AddField(
            model_name='addition',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_addition', to='user.staffprofile'),
        ),
    ]
