# Generated by Django 4.2.17 on 2025-02-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crucial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='version',
            field=models.CharField(blank=True, choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=8, null=True),
        ),
    ]
