# Generated by Django 4.2.17 on 2025-02-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('crucial', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='receive',
            name='fee_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crucial.feehead'),
        ),
        migrations.AddField(
            model_name='receive',
            name='income_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_receipts', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='receive',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expense_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payments', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payments', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='mainbalance',
            name='cash_ledger',
            field=models.ForeignKey(limit_choices_to={'category__name': 'Asset'}, on_delete=django.db.models.deletion.PROTECT, to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sub_ledg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.entryhead'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.ledgercategory'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='incomeitemlist',
            name='incometype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.incomehead'),
        ),
        migrations.AddField(
            model_name='expenseitemlist',
            name='expensetype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.expensehead'),
        ),
        migrations.AddField(
            model_name='contra',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='contra',
            name='from_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_out', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='contra',
            name='to_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_in', to='accounting.ledger'),
        ),
    ]
