# Generated by Django 4.2.17 on 2025-05-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_staffprofile_subject'),
        ('accounting', '0003_alter_ledgerentry_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.staffprofile'),
        ),
    ]
