# Generated by Django 4.2.17 on 2025-02-05 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crucial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendancelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendancelog',
            name='student_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_attendance_logs', to='attendance.studentattendance'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attend_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attend', to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attend_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendancelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendancelog',
            name='staff_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_logs', to='attendance.staffattendance'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attend_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attend', to='user.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attend_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='periodattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_attend_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodattendance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_student_attend', to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='periodattendance',
            name='period_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_attend', to='core.periodconfig'),
        ),
        migrations.AddField(
            model_name='periodattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_attend_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleavetype', to='attendance.leavetype'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='hostelattendancelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelattendancelog',
            name='hostel_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_attendance_logs', to='attendance.hostelattendance'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_student_attend_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_student_attend', to='crucial.hostel'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_student_attend_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.admission_year'),
        ),
    ]
